### ISSUE TITLE
[BaseMultivariate] OutOfMemoryError on GPU

### ISSUE THREAD

**Issue by Antoine-Schwartz** [Nixtla/neuralforecast#1202]
### What happened + What you expected to happen

Hello Nixtla community,

I suspect a bug, or a sampling optimization problem, especially for `BaseMultivariate` models!

First of all, the number of additional columns in `df` (exogenous variables) has a strong impact on memory demand, even if they are not taken into account by the model (see the example below with `TSMixer`). I think this problem also exists for univariate solutions, but the impact is less exponential than for multivariate ones.

Secondly, even if you keep only the necessary columns, it's still hard for the samples to fit into GPU memory during training when you have tens of thousands series. 
I know that multivariate scales badly with a number of series, but it seems feasible if I refer to [TSMixer's paper](https://arxiv.org/pdf/2303.06053): experiments on M5 data (30,490 series with static features) with an NVIDIA Tesla V100 GPU.

### Versions / Dependencies

neuralforecast==1.7.5
Databricks Runtime: [14.3 LTS ML](https://docs.databricks.com/en/release-notes/runtime/14.3lts-ml.html)
GPU: [g5.8xlarge](https://aws.amazon.com/fr/ec2/instance-types/g5/)

### Reproduction script

```
n_series = 30000

# Add columns to df (static features) until memory crash
for n_static_features in range(0, 10):

    print(f"====== Nb of static feat: {n_static_features} ======")

    df = generate_series(
        n_series=n_series,
        freq="W",
        min_length=208,
        max_length=208,
        equal_ends=True,
        n_static_features=n_static_features,
    )

    model = TSMixer(
        h=52,
        input_size=104,
        n_series=n_series, 
        max_steps=60,
        val_check_steps=60,
        enable_model_summary=False,
    )
    nf = NeuralForecast(models=[model], freq='W')

    nf.fit(df=df)

    del df, model, nf
    gc.collect()
    torch.cuda.empty_cache()
    time.sleep(60)
```

**Crash from 4 static features**:
`OutOfMemoryError: CUDA out of memory. Tried to allocate 10.88 GiB. GPU 0 has a total capacity of 21.99 GiB of which 10.24 GiB is free. Process 31599 has 11.74 GiB memory in use. Of the allocated memory 949.35 MiB is allocated by PyTorch, and 10.52 GiB is reserved by PyTorch but unallocated.`

<img width="275" alt="image" src="https://github.com/user-attachments/assets/390abc24-677f-4790-8c91-b652e31bb54d">

### Issue Severity

High: It blocks me from completing my task.

**Comment by elephaint** [comment]
The following code trains just fine on max 14 GB GPU mem on my RTX 3090, meaning that it should run fine on any V100 too. 

You should avoid looping through tryouts, even with all the `gc` and `empty_cache` shenanigans it's nearly impossible to properly clear the memory. 

```
from neuralforecast.models import TSMixer
from utilsforecast.data import generate_series
import torch

n_series = 30490
n_static_features = 10

df = generate_series(
    n_series=n_series,
    freq="W",
    min_length=208,
    max_length=208,
    equal_ends=True,
    n_static_features=0,
)

model = TSMixer(
    h=52,
    input_size=104,
    n_series=n_series, 
    max_steps=60,
    val_check_steps=60,
    enable_model_summary=False,

)
nf = NeuralForecast(models=[model], freq='W')

nf.fit(df=df)
```

**Comment by Antoine-Schwartz** [comment]
Hello, thanks @elephaint for you answer.

In you example you still have `n_static_features=0` in the `generate_series`call. Does it really run on 14GB of your RTX 3090 with 10 features?

You're right, the combo `gc` + `empty_cache` isn't perfect, but it does allow you to get very close to 0 memory usage for testing, as shown by the graph above :)

**Comment by elephaint** [comment]
Argh, I was stupid. `TSMixer` doesn't even support exogenous variables, so you're starting with the wrong model. You should use `TSMixerx` and use the correct way of [incorporating exogenous variables](https://nixtlaverse.nixtla.io/neuralforecast/docs/capabilities/exogenous_variables.html). 

The following runs with a very low mem cost on my GPU:

```
from neuralforecast import NeuralForecast
from neuralforecast.models import TSMixerx
from utilsforecast.data import generate_series

n_series = 30490
n_static_features = 10

df = generate_series(
    n_series=n_series,
    freq="W",
    min_length=208,
    max_length=208,
    equal_ends=True,
    n_static_features=10,
)

static_df = df.groupby("unique_id", as_index=False).first().drop(columns=["y", "ds"])

model = TSMixerx(
    h=52,
    input_size=104,
    n_series=n_series, 
    max_steps=5,
    val_check_steps=60,
    enable_model_summary=False,
    stat_exog_list=[f"static_{i}" for i in range(n_static_features)],
)
nf = NeuralForecast(models=[model], freq='W')

nf.fit(df=df, static_df=static_df)
```

I assume this closes the issue?

**Comment by jmoralez** [comment]
I think these are indeed two issues.

1. I think we currently build the dataset with every column in the dataframe without checking if they're actually used by the models, we can probably be smarter than this and filter it first to keep only the features that will be used.
2. Does the error happen here? https://github.com/Nixtla/neuralforecast/blob/642ced4f0e79682ad125779e08ea419968642c0b/neuralforecast/common/_base_multivariate.py#L169
  The windows are a view so they don't consume memory until we materialize them, we can try keeping them as a view and just materialize the sample that is taken below https://github.com/Nixtla/neuralforecast/blob/642ced4f0e79682ad125779e08ea419968642c0b/neuralforecast/common/_base_multivariate.py#L179-L187

**Comment by Antoine-Schwartz** [comment]
Exactly @jmoralez, for the first issue, it's actually what I suspected, for the 2nd it's indeed at this line that the error happens.
However, I don't understand how the code can pass on a 14GB GPU.

I'll try running it on other types of graphics card...

**Comment by Antoine-Schwartz** [comment]
I found a solution to make it fit in memory (thanks to @elephaint ).

**Issue 1**: not yet fixed, but it will be in a future version. In the meantime, a simple upstream filter on the columns used as exogenous variables is enough.

**Issue 2**: improved in the latest version, but still not enough to fit in memory.

**The trick**: Increase the `step_size`! For example, with a `step_size=4`, memory usage is reduced by a factor of 4, with a theoretically reasonable impact on performances.
